name: Release
on:
  push:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.package_version.outputs.next_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Prepare Release
        id: package_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export NEXT_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo "next_version=${NEXT_VERSION}" >> $GITHUB_OUTPUT
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  post-release:
    needs: release
    if: ${{ needs.release.outputs.next_version != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "status": "${{ job.status }}",
              "version": "${{ needs.release.outputs.next_version }}",
              "link": "https://github.com/nala5539/npm-test/releases/tag/v${{ needs.release.outputs.next_version }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
